from __future__ import annotations

from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import pandas as pd

from event_impact_model.utils.io import ensure_dir
from event_impact_model.utils.log import get_logger

log = get_logger("build_report")


def _read_csv(path: Path) -> pd.DataFrame | None:
    if not path.exists():
        log.warning(f"Missing: {path}")
        return None
    return pd.read_csv(path)


def plot_caar(event_summary_csv: Path, out_png: Path) -> None:
    df = _read_csv(event_summary_csv)
    if df is None or df.empty or not {"tau", "caar"}.issubset(df.columns):
        log.warning("Skipping CAAR plot (missing columns).")
        return

    df = df.sort_values("tau")
    plt.figure()
    plt.plot(df["tau"], df["caar"])
    plt.axhline(0.0)
    plt.xlabel("Tau (trading days)")
    plt.ylabel("CAAR")
    plt.title("CAAR over event window")
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()
    log.info(f"Saved: {out_png}")


def plot_equity(daily_csv: Path, out_png: Path, title: str) -> None:
    df = _read_csv(daily_csv)
    if df is None or df.empty:
        return
    if "date" not in df.columns:
        return

    df["date"] = pd.to_datetime(df["date"])
    cols = [c for c in ["equity_gross", "equity_net"] if c in df.columns]
    if not cols:
        log.warning(f"Skipping equity plot (no equity cols) for {daily_csv}")
        return

    plt.figure()
    for c in cols:
        plt.plot(df["date"], df[c], label=c)
    plt.xlabel("Date")
    plt.ylabel("Equity")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(out_png, dpi=150)
    plt.close()
    log.info(f"Saved: {out_png}")


def load_cv_metrics(processed: Path) -> pd.DataFrame:
    rows: list[pd.DataFrame] = []

    ridge = processed / "cv_metrics.csv"
    lgbm = processed / "cv_metrics_lgbm.csv"

    d1 = _read_csv(ridge)
    if d1 is not None and not d1.empty:
        d1["model_file"] = "ridge/logit"
        rows.append(d1)

    d2 = _read_csv(lgbm)
    if d2 is not None and not d2.empty:
        d2["model_file"] = "lgbm"
        rows.append(d2)

    if not rows:
        return pd.DataFrame()

    return pd.concat(rows, ignore_index=True)


def summarize_cv(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df

    if "model" not in df.columns:
        df["model"] = df.get("model_file", "unknown")

    keep = [
        c
        for c in ["model", "mse", "r2", "pearson", "spearman", "hit_rate", "accuracy"]
        if c in df.columns
    ]
    out = (
        df[keep]
        .groupby("model", dropna=False)
        .mean(numeric_only=True)
        .reset_index()
        .sort_values("model")
    )
    return out


def load_backtest_summaries(reports: Path) -> pd.DataFrame:
    files = [
        ("engine", reports / "backtest_engine_summary.csv"),
        ("engine_vt10", reports / "backtest_engine_summary_vt10.csv"),
        ("costed_eventlevel", reports / "backtest_costed_eventlevel_overall.csv"),
    ]

    rows: list[dict] = []
    for name, p in files:
        df = _read_csv(p)
        if df is None or df.empty:
            continue
        r = df.iloc[0].to_dict()
        r["variant"] = name
        rows.append(r)

    return pd.DataFrame(rows)


def write_markdown_report(
    out_md: Path,
    cv_summary: pd.DataFrame,
    bt_summary: pd.DataFrame,
    figs_dir: Path,
) -> None:
    lines: list[str] = []
    lines.append("# Event Impact Model — Report\n")
    lines.append("This report is autogenerated from the current pipeline artifacts.\n")

    lines.append("## Figures\n")
    caar_png = figs_dir / "caar.png"
    if caar_png.exists():
        lines.append(f"### CAAR\n\n![](figures/{caar_png.name})\n")

    eq_png = figs_dir / "equity_engine.png"
    if eq_png.exists():
        lines.append(f"### Equity Curve (Engine)\n\n![](figures/{eq_png.name})\n")

    eq_vt_png = figs_dir / "equity_engine_vt10.png"
    if eq_vt_png.exists():
        lines.append(
            f"### Equity Curve (Engine, vol target 10%)\n\n![](figures/{eq_vt_png.name})\n"
        )

    lines.append("## Cross-Validation Summary\n")
    if cv_summary.empty:
        lines.append("_No CV metrics found._\n")
    else:
        lines.append(cv_summary.to_markdown(index=False))
        lines.append("")

    lines.append("## Backtest Summary\n")
    if bt_summary.empty:
        lines.append("_No backtest summaries found._\n")
    else:
        cols = [
            c
            for c in [
                "variant",
                "sharpe_gross",
                "sharpe_net",
                "maxdd_gross",
                "maxdd_net",
                "mean_turnover",
                "mean_cost",
                "avg_active",
                "n_pairs",
                "mean_net",
                "hit_rate",
            ]
            if c in bt_summary.columns
        ]
        view = bt_summary[cols] if cols else bt_summary
        lines.append(view.to_markdown(index=False))
        lines.append("")

    lines.append("## Notes\n")
    lines.append(
        "- Sensitivity grid is for robustness; we do NOT select the best row for trading.\n"
    )

    out_md.write_text("\n".join(lines), encoding="utf-8")
    log.info(f"Saved: {out_md}")


def main() -> None:
    root = Path(".")
    processed = root / "data" / "processed"
    reports = root / "reports"
    figs = reports / "figures"

    ensure_dir(reports)
    ensure_dir(figs)

    plot_caar(reports / "event_study_summary.csv", figs / "caar.png")
    plot_equity(
        reports / "backtest_engine_daily.csv",
        figs / "equity_engine.png",
        "Equity (Backtest Engine)",
    )
    plot_equity(
        reports / "backtest_engine_daily_vt10.csv",
        figs / "equity_engine_vt10.png",
        "Equity (Backtest Engine, Vol Target 10%)",
    )

    cv = load_cv_metrics(processed)
    cv_summary = summarize_cv(cv)
    bt_summary = load_backtest_summaries(reports)

    write_markdown_report(
        reports / "REPORT.md",
        cv_summary=cv_summary,
        bt_summary=bt_summary,
        figs_dir=figs,
    )


if __name__ == "__main__":
    main()
